### ISSUE TITLE
Error compiling for board Arduino Mega or Mega 2560

### ISSUE THREAD

**Issue by EliTe991** [JanisDavidsons/aquarium_controller#1]
hello, i have a problem whit upoload code. error text is down below.

[Error compiling for board Arduino Mega or Mega 2560..txt](https://github.com/JanisDavidsons/aquarium_controller/files/4611221/Error.compiling.for.board.Arduino.Mega.or.Mega.2560.txt)

**Comment by JanisDavidsons** [comment]
Hi, which IDE are you using?

**Comment by EliTe991** [comment]
ide 1.8.12

**Comment by JanisDavidsons** [comment]
![image](https://user-images.githubusercontent.com/42038039/81596468-cec74a00-93cc-11ea-9495-d7de8c02b4d7.png)
This is written using Sloeber as IDE. If you are using Arduino IDE, you will have to modify code a lot, to make it working on Arduino IDE. 
Can you send me a screenshot of IDE

**Comment by EliTe991** [comment]
![image](https://user-images.githubusercontent.com/62514711/81597333-dd5e3300-93c5-11ea-8d1e-7ed9253cdc06.png)

if I installed a Sloeber, would it work then?

**Comment by JanisDavidsons** [comment]
It will work. But you will have to learn Sloeber. Which touch screen you have? I have OPEN-SMART Shield with HX8352B chip. If you have something else, then different configuration is needed. This is how the screen will look like. 
![IMG_20200511_212427](https://user-images.githubusercontent.com/42038039/81597776-ee5f7200-93ce-11ea-8343-94e7edf37e9f.jpg) 
![IMG_20200511_212432](https://user-images.githubusercontent.com/42038039/81597781-eef80880-93ce-11ea-9491-334cbec7ad50.jpg)


![IMG_20200511_212414](https://user-images.githubusercontent.com/42038039/81597770-ed2e4500-93ce-11ea-8037-7c71a46b21f5.jpg)

**Comment by EliTe991** [comment]
I have an shield LCD with a touchscreen, it works with the MCUFRIEND library, Driver IC ILI9486
Resolution 480*320 (Pixel)
